---
- hosts: localhost
  gather_facts: false
  name: Setup ONTAP Cluster

  vars_files:
  - vars/var_file.yml
  - vars/licenses.yml
#     vars_prompt:
#  - name: "password"
#    prompt: "Password:"

  vars:
    login: &login
      hostname: "{{ cluster_name }}"
      username: "{{ username }}"
      password: "netapp01"
      https: true
      validate_certs: false

  tasks:
  - name: Add licenses
    na_ontap_license:
      state: present
      <<: *login 
      license_codes: "{{ ntap_licenses }}"
  - name: Assign unowned disks
    na_ontap_disks:
      node: "{{ item }}"
      <<: *login 
    with_items:
      - vsim-01

  - name: Create Aggrs
    na_ontap_aggregate:
      state: "{{ state }}"
      name: "{{ item.name }}"
      nodes: "{{ item.node }}"
      disk_count: 25
      raid_size: 25
      <<: *login 
    with_items:
      - { name: "aggr1", node: "vsim-01" }

