---
- hosts: localhost
  name: Setup SVM
  vars_files:
  - vars/var_file.yml
  - vars/password.yml
  vars:
    login: &login
      hostname: "{{ cluster_name }}"
      username: "{{ username }}"
      password: "netapp01"
      https: true
      validate_certs: false
  tasks:
  - name: Create SVM
    na_ontap_svm:
      state: "{{ state }}"
      name: "{{ vserver }}"
      root_volume: "{{ vserver}}_root"
      root_volume_aggregate: "{{ vserver_aggr }}"
      root_volume_security_style: unix
      <<: *login 

  - name: Create interface
    na_ontap_interface:
      state: "{{ state }}"
      interface_name: "{{ vserver }}_mgmt_data_1"
      home_port: e0d
      home_node: vsim-01
      role: data
      protocols: nfs
      admin_status: up
      failover_policy: local-only
      firewall_policy: mgmt-nfs
      is_auto_revert: true
      address: "{{ vserver_address }}"
      netmask: "{{ vserver_netmask }}"
      vserver: "{{ vserver }}"
      <<: *login 

  - name: change nfs status
    na_ontap_nfs:
      state: "{{ state }}"
      service_state: started
      vserver: "{{ vserver }}"
      nfsv3: enabled
      nfsv4: disabled
      nfsv41: disabled
      tcp: enabled
      udp: enabled
      vstorage_state: disabled
      <<: *login 

  - name: Setup default rules
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: default
      vserver: "{{ vserver }}"
      client_match: "{{ vserver_client }}"
      ro_rule: any
      rw_rule: none
      super_user_security: none
      <<: *login 
