---
- hosts: localhost
  name: Setup ONTAP
  vars_files:
  - vars/var_file.yml
  - vars/password.yml

  vars:
    login: &login
      hostname: "{{ cluster_name }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

  tasks:
  - name: Create Policy
    na_ontap_export_policy:
      state: "{{ state }}"
      name: "{{ vserver_policy }}"
      vserver: "{{ vserver }}"
      <<: *login 
  - name: Setup rules
    na_ontap_export_policy_rule:
      state: "{{ state }}"
      policy_name: "{{ vserver_policy }}"
      vserver: "{{ vserver }}"
      client_match: "{{ vserver_client }}"
      ro_rule: sys
      rw_rule: sys
      super_user_security: sys
      <<: *login 
  - name: Create volume
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ vserver_volname }}"
      aggregate_name: "{{ vserver_aggr }}"
      size: 1
      size_unit: gb
      policy: "{{ vserver_policy }}"
      junction_path: "/{{ vserver_volname }}"
      space_guarantee: "none"
      vserver: "{{ vserver }}"
      <<: *login 